version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: tempos-api
    env_file:
      - backend/.env
    volumes:
      - ./data:/app/data
    ports:
      - "8000:8000"
    depends_on:
      - ollama

  ui:
    image: python:3.11-slim
    container_name: tempos-ui
    working_dir: /ui
    volumes:
      - ./frontend/streamlit_app:/ui
    environment:
      - API_URL=http://api:8000/api/v1
    command: bash -lc "pip install streamlit requests && streamlit run app.py --server.address=0.0.0.0 --server.port=8501"
    ports:
      - "8501:8501"
    depends_on:
      - api

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 30s
      timeout: 5s
      retries: 5

volumes:
  ollama_data:
